name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: h100

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file micro-benchmarks/nccl-tests/nccl-tests.Dockerfile --tag nccl-tests:$(date +%s)
